### ISSUE TITLE
Question: How to run tests as an authenticated user

### ISSUE THREAD

**Issue by ManuelMartinDev** [thetutlage/japa#42]
Is there a way to test api endpoints that require auth? 
Example:
I want to test the creation of a organization in my api endpoint, but to create it I need to be an authenticated user

I could not find it in the docs, right now what I'm doing is call the login endpoint and save the response cookies to use in future requests but it is a very ugly way to do it specially when having tests in different files that doesn't run in a controlled order
¿Is there a better way to do it ?

**Comment by hmartiins** [comment]
Hi @ManuelMartinDev. I will show you the way I am using to test routes that require authentication, I am using the Supertest library as well.

In my application I need to test the user's update, but for that the user needs to be logged in, I am generating a JWT token when the user logs into the application. To proceed with the update we need to pass the Bearer token in the request header, and I'm doing it this way.

```tsx
await supertest(BASE_URL).post('/users').send(user);
const auth = await supertest(BASE_URL)
.post('/auth/login')
.send({ email: user.email, password: user.password });

const updateResponse = await supertest(BASE_URL)
  .put('/users')
  .auth(auth.body.token, { type: auth.body.type })
  .send(user2);

assert.equal(
  JSON.stringify(updateResponse.body),
  JSON.stringify({ success: 'User updated' }),
);
assert.equal(updateResponse.statusCode, 200);
```

The response from the login route already gives me the value of the token and the type of token I am using, all of which I need to pass in the auth method.

In my case I am using the supertest library to check authentication rather than Japa. I don't know if this was in fact what you needed, but I am using this methodology, Japa + Supertest to test the API routes, and it has been working very well!

If you want you can use [Hook before](https://github.com/thetutlage/japa#test-groups) offered by the Japa library, to authenticate the user and save their response, what you should do after that is just pass the login response in the auth method of the routes that require authentication. Using the hook before, to do this, you decrease the code of your test, since you don't need to create a user and authenticate every time you use it

**Comment by thetutlage** [comment]
Outside of the scope of Japa itself and also I believe @hmartiins answer helps :)
